version: '3.8'

services:
  proxy:
    build: ./nginx
    container_name: cont_proxy
    ports:
      - "80:80"
    networks:
      - proxy-admin-network
      - proxy-clientes-network
      - proxy-api-network
    depends_on:
      - web-publica
      - web-admin
      - api

  web-publica:
    build: ./web-publica
    container_name: cont_web-publica
    networks:
      - proxy-clientes-network
      - clientes-api-network
    ports:
      - "3001:80"

  web-admin:
    build: ./web-admin
    container_name: cont_web-admin
    networks:
      - proxy-admin-network
      - admin-api-network
    ports:
      - "3002:80"

  api:
    build: ./api
    container_name: cont_api
    networks:
      - proxy-api-network
      - admin-api-network
      - clientes-api-network
      - api-bd-network
    ports:
      - "3003:5000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=distributec
      - DATABASE_PASSWORD=distributec123
      - DATABASE_NAME=inventario
    depends_on:
      - database
  database:
    image: mysql:8.0
    container_name: cont_database
    environment:
      MYSQL_ROOT_PASSWORD: admin123 
      MYSQL_DATABASE: inventario
      MYSQL_USER: distributec
      MYSQL_PASSWORD: distributec123
    ports:
      - "3306:3306"
    volumes:
      - db_info:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - api-bd-network
volumes:
  db_info:

networks:
  proxy-admin-network:
    driver: bridge
  proxy-clientes-network:
    driver: bridge
  proxy-api-network:
    driver: bridge
  admin-api-network:
    driver: bridge
  clientes-api-network:
    driver: bridge
  api-bd-network:
    driver: bridge

